# Module: NumPy Assignments
## Lesson: NumPy

In [83]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# ### Assignment 1: Array Creation and Manipulation

# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
arr = np.array(np.random.randint(1,20, size=(5,5)))
print("Original Array:\n", arr)
arr[:, 2] = 1
print("Modified Array with third column as 1:\n", arr)

# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
arr = np.arange(1,17).reshape(4,4)
print("Original Array:\n", arr)
np.fill_diagonal(arr, 0)
print("Modified Array with diagonal elements as 0:\n", arr)


### Assignment 2: Array Indexing and Slicing

# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
arr = np.arange(1, 37).reshape(6, 6)
print("Original Array:\n", arr)
subArr = arr[3:5, 2:4]
print("Sub-array (3rd to 5th rows and 2nd to 4th columns):\n", subArr)


# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
arr = np.random.randint(1, 20, size=(5, 5))
print("Original Array:\n", arr) 
border_elements = np.concatenate((arr[0, :], arr[-1, :], arr[1:-1, 0], arr[1:-1, -1]))
print("Border elements:\n", border_elements)

### Assignment 3: Array Operations

# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
arr1 = np.random.randint(1, 17, size=(3, 4))
arr2 = np.random.randint(1, 17, size=(3, 4))

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Element-wise Addition:\n", arr1 + arr2)
print("Element-wise Subtraction:\n", arr1 - arr2)
print("Element-wise Multiplication:\n", arr1 * arr2)
print("Element-wise Division:\n", arr1 / arr2)

# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
arr = np.arange(1, 17).reshape(4, 4)
sum_row = np.sum(arr, axis=1)
sum_col = np.sum(arr, axis=0)

print("Original Array:\n", arr)
print("Row-wise Sum:\n", sum_row)
print("Column-wise Sum:\n", sum_col)


### Assignment 4: Statistical Operations

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
arr = np.random.randint(1, 26, size=(5, 5))
mean = np.mean(arr)
median = np.median(arr)
sd = np.std(arr)
variance = np.var(arr)

print("Array:\n", arr)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", sd)
print("Variance:", variance)

# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

arr = np.arange(1,10).reshape(3,3)
mean = np.mean(arr)
sd = np.std(arr)
normalized_arr = (arr - mean) / sd

print("Original Array:\n", arr)
print("Normalized Array:\n", normalized_arr)
print("Mean of Normalized Array:", np.mean(normalized_arr))
print("Standard Deviation of Normalized Array:", np.std(normalized_arr))

### Assignment 5: Broadcasting

# 1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
# Broadcasting example
arr = np.random.randint(1, 10, size=(3,3))
arr1d = np.array([1, 2, 3])
print("Original 2D Array:\n", arr)
result = arr + arr1d
print("Result after adding 1D array to each row:\n", result)

# 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
arr = np.random.randint(1, 16, size=(4,4))
arr1d = np.arange(1, 5)
print("Original 2D Array:\n", arr)
print(arr1d[:, np.newaxis])
result = arr - arr1d[:, np.newaxis]
print("Result after subtracting 1D array from each column:\n", result)


### Assignment 6: Linear Algebra

# 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
arr = np.random.randint(1,10, size=(3,3))
det = np.linalg.det(arr)
inv = np.linalg.inv(arr) if det != 0 else "Matrix is singular, inverse does not exist"
eigenvalues, eigenvectors = np.linalg.eig(arr)

print("Matrix:\n", arr)
print("Determinant:", det)  
print("Inverse:\n", inv)
print("Eigenvalues:\n", eigenvalues)

# 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
arr1 = np.random.randint(1, 10, size=(2, 3))
arr2 = np.random.randint(1, 10, size=(3, 2))

matrix_product = np.dot(arr1, arr2)
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)   
print("Matrix Multiplication Result:\n", matrix_product)


### Assignment 7: Advanced Array Manipulation

# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
arr = np.arange(1, 10).reshape(3, 3)
reshaped1 = arr.reshape(1, 9)
reshaped2 = arr.reshape(9, 1)
print("Original Array:\n", arr)
print("Reshaped to (1, 9):\n", reshaped1)
print("Reshaped to (9, 1):\n", reshaped2)

# 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).
arr = np.random.randint(1, 21, size=(5, 5))
print("Array:\n", arr)
flatten = arr.flatten()
print("Flatten Array:\n", flatten)
reshaped = flatten.reshape(5, 5)
print("Reshaped Array:\n", reshaped)

### Assignment 8: Fancy Indexing and Boolean Indexing

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
arr = np.random.randint(1, 26, size=(5, 5))

# Fancy Indexing to extract corner elements
corners = arr[[0, 0, 4, 4], [0, 4, 0, 4]]
print("Array:\n", arr)
print("Corner elements:\n", corners)


# 2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.
arr = np.random.randint(1, 21, size=(4, 4))
print("Original Array:\n", arr)

arr[arr>10] = 10
print("Modified Array with elements greater than 10 set to 10:\n", arr)

### Assignment 9: Structured Arrays

# 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
arr = np.array([('Alice', 25, 55.5), ('Bob', 22, 70.2), ('Charlie', 30, 68.0)],
               dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
np.sort(arr, order='age')
print("Structured Array sorted by age:\n", np.sort(arr, order='age'))
# 2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.
arr = np.array([(1,2), (2,3)], dtype=([('x', 'i4'), ('y', 'i4') ]))
print("Structured Array:\n", arr)
distance = np.linalg.norm(arr['x'] - arr['y'])
print("Euclidean distance between points:\n", distance)

### Assignment 10: Masked Arrays

# 1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
arr = np.random.randint(1, 17, size=(4, 4))
masked = np.ma.masked_greater(arr, 10)
print("Original Array:\n", arr)
print("Masked Array (elements > 10 are masked):\n", masked) 


# 2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.
array = np.random.randint(1, 10, size=(3, 3))
masked_array = np.ma.masked_array(array, mask=np.eye(3, dtype=bool))
mean_unmasked = masked_array.mean()
masked_array.fill_vapl;lue = mean_unmasked

Original Array:
 [[16  4 13  3 10]
 [12 13 16  1  9]
 [ 9  3  4  7  1]
 [19  9  7  5 15]
 [ 6 18  2 17  1]]
Modified Array with third column as 1:
 [[16  4  1  3 10]
 [12 13  1  1  9]
 [ 9  3  1  7  1]
 [19  9  1  5 15]
 [ 6 18  1 17  1]]
Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array with diagonal elements as 0:
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]
Original Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array (3rd to 5th rows and 2nd to 4th columns):
 [[21 22]
 [27 28]]
Original Array:
 [[ 8 13 12 13  5]
 [16  2 13  9 10]
 [ 8 10 11 11  3]
 [11  5  4 16  9]
 [ 5  7 18  8  7]]
Border elements:
 [ 8 13 12 13  5  5  7 18  8  7 16  8 11 10  3  9]
Array 1:
 [[16  3  2  8]
 [ 1  7  6 15]
 [10  4 11 10]]
Array 2:
 [[ 2  9 12  3]
 [ 7 10  7  1]
 [ 6  6  8 11]]
Element-wise Addition:
 [[18 12 14 11]
 [ 8 17 13 16]
 [16 10 19 21]]
Ele

Original Array:
 [[ 1 15  6 11]
 [10  3 15 11]
 [ 2 14 14 11]
 [ 7 13  9 12]]
Masked Array (elements > 10 are masked):
 [[1 -- 6 --]
 [10 3 -- --]
 [2 -- -- --]
 [7 -- 9 --]]
